services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_dpharma
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_dpharma
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
